version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fastapi-backend

volumes:
  postgres-data:

networks:
  fastapi-backend: